### ISSUE TITLE
Incorrect calculation on overflows

### ISSUE THREAD

**Issue by izbushka** [YiannisBourkelis/Uptime-Library#3]
Seems like the code is loosing a few milliseconds (4,294,967,295 - uptime::m_last_milliseconds)  when millis counter rollover

**Comment by YiannisBourkelis** [comment]
The millis() function is by itself not 100% accurate in the long run. If the board has a crystal oscillator instead of a resonator it might be much more accurate. Also board temperature and aging effect millis function. However if you think that we can Improve the accuracy of the calculations please send me a pull request and I will take a look at it.
